version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: prompt-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/prompt
      - JWT_SECRET=your_super_secret_jwt_key_for_prompt_app
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - prompt-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prompt-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - prompt-network

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: prompt-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - prompt-network

networks:
  prompt-network:
    driver: bridge

volumes:
  mongodb_data: